export const TEAM_COLORS = [
    { name: 'Default (MPC Purple)', color: '#420039' },
    { name: "TCU Horned Frogs", color: "#4D1979" },
    { name: "Michigan Wolverines", color: "#00274C" },
    { name: "Washington Huskies", color: "#4B2E83" },
    { name: "Texas Longhorns", color: "#BF5700" },
    { name: "Alabama Crimson Tide", color: "#9E1B32" },
    { name: "Georgia Bulldogs", color: "#BA0C2F" },
    { name: "Oregon Ducks", color: "#154733" },
    { name: "Ohio State Buckeyes", color: "#BB0000" },
    { name: "LSU Tigers", color: "#461D7C" },
    { name: "Tennessee Volunteers", color: "#FF8200" },
    { name: "Clemson Tigers", color: "#F56600" },
    { name: "Florida State Seminoles", color: "#782F40" },
    { name: "Oklahoma State Cowboys", color: "#FF7300" },
    { name: "Notre Dame Fighting Irish", color: "#0C2340" },
    { name: "USC Trojans", color: "#990000" },
    { name: "Penn State Nittany Lions", color: "#041E42" },
] as const;
